name: ubuntu-kr-qr-kiosk
version: 0.1.0
summary: Kiosk app for Ubuntu KR event QR Check in
description: Kiosk app for Ubuntu KR event QR Check in
compression: lzo

confinement: strict
base: core22
grade: stable

apps:
  ubuntu-kr-qr-kiosk:
    command-chain: &_command-chain
    - bin/graphics-core22-wrapper
    - bin/wayland-launch
    command: &_command bin/ubuntu_kr_qr_kiosk
    # extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    # extensions: [gnome] 
    plugs: &_plugs
    - opengl
    - wayland
    - network
    - raw-usb
    - home
    - process-control
    - system-observe
    - hardware-observe
    # slots:
    #   - dbus-ubuntu-kr-qr-kiosk
    environment: &_environment
      XDG_DATA_HOME: $SNAP_USER_DATA
      XDG_DATA_DIRS: $SNAP/usr/share
      GDK_GL: gles
  daemon:
    daemon: simple
    restart-delay: 3s
    restart-condition: always
    command-chain: *_command-chain
    command: *_command
    plugs: *_plugs
    environment: *_environment
  usbserver:
    command: bin/usbserver-launch
    daemon: simple
    restart-delay: 5s
    restart-condition: always

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

environment:
  # Other, generally useful environment settings...
  # LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib
  # XDG config
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  XDG_CONFIG_DIRS: $SNAP/etc/xdg
  XDG_DATA_DIRS:   $SNAP/usr/local/share:$SNAP/usr/share
  # XKB config
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
  # Font
  FONTCONFIG_PATH: ${SNAP}/etc/fonts/conf.d
  FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf
  # Enforce locale
  LC_ALL: ko_KR.UTF-8

layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d
  # Other, generally useful paths
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/local/share/fonts: 
    bind: $SNAP/usr/share/fonts
  # GTK
  /usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0
  /usr/lib/${CRAFT_ARCH_TRIPLET}/gtk-3.0:
    bind: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET}/gtk-3.0
  /usr/share/mime:
    bind: $SNAP/usr/share/mime
  /etc/gtk-3.0:
    bind: $SNAP/etc/gtk-3.0
# slots:
  # dbus-ubuntu-kr-qr-kiosk: # adjust accordingly to your app name
  #   interface: dbus
  #   bus: session
  #   name: org.ubuntu-kr.kiosk # adjust accordingly to your app name and
  
parts:
  # gsettings, pixbuf and immodules are not needed by all snaps,
  # but they are so common a requirement include them here
  gsettings+pixbuf+immodules:
    plugin: nil
    build-packages:
      - libgdk-pixbuf2.0-0
      - librsvg2-common
      - shared-mime-info
      - libgtk-3-0
    override-build: |
      craftctl default
      # Update mime database
      update-mime-database ${CRAFT_PART_INSTALL}/usr/share/mime
      # build immodules cache
      mkdir -p ${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET}/gtk-3.0/3.0.0/
      /usr/lib/${CRAFT_ARCH_TRIPLET}/libgtk-3-0/gtk-query-immodules-3.0 > ${CRAFT_PART_INSTALL}/usr/lib/${CRAFT_ARCH_TRIPLET}/gtk-3.0/3.0.0/immodules.cache
    stage-packages:
      - librsvg2-common
      - gsettings-desktop-schemas
      - libglib2.0-bin
    override-prime: |
      craftctl default
      # Compile the gsettings schemas
      /usr/lib/${CRAFT_ARCH_TRIPLET}/glib-2.0/glib-compile-schemas "$CRAFT_PRIME/usr/share/glib-2.0/schemas"
      # Index the pixbuf loaders
      LOADERS_PATH=$(echo ${CRAFT_PRIME}/usr/lib/${CRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/*/loaders)
      QUERY_LOADERS=/usr/lib/${CRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders
      GDK_PIXBUF_MODULEDIR=${LOADERS_PATH} ${QUERY_LOADERS} > ${LOADERS_PATH}/../loaders.cache
      sed s!$CRAFT_PRIME!!g --in-place ${LOADERS_PATH}/../loaders.cache

  # Some utility scripts for setting up the Wayland environment
  setup:
    plugin: dump
    source: snap-launch
    override-build: |
      # The plugs needed to run Wayland. (wayland-launch checks them, setup.sh connects them)
      # You may add further plugs here if you want these options
      PLUGS="opengl wayland graphics-core22 home raw-usb process-control system-observe hardware-observe"
      sed --in-place "s/%PLUGS%/$PLUGS/g" $CRAFT_PART_BUILD/bin/wayland-launch
      sed --in-place "s/%PLUGS%/$PLUGS/g" $CRAFT_PART_BUILD/bin/setup.sh
      craftctl default
    stage-packages:
      - inotify-tools

  # flutter-git:
  #   source: https://github.com/flutter/flutter.git
  #   source-tag: 3.13.2
  #   source-depth: 1
  #   plugin: nil
  #   override-build: |
  #     mkdir -p $CRAFT_PART_INSTALL/usr/bin
  #     mkdir -p $CRAFT_PART_INSTALL/usr/libexec
  #     cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
  #     ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
  #     $CRAFT_PART_INSTALL/usr/bin/flutter doctor
  #   build-packages:
  #     - clang
  #     - cmake
  #     - curl
  #     - libgtk-3-dev
  #     - ninja-build
  #     - unzip
  #     - xz-utils
  #     - zip
  #   override-prime: ''

  ubuntu-kr-qr-kiosk:
    # after: [flutter-git]
    source: .
    source-type: git
    plugin: nil
    # plugin: flutter
    # flutter-target: lib/main.dart # The main entry-point file of the application
    build-snaps:
      - flutter/latest/stable
    build-environment:
      - C_INCLUDE_PATH: /snap/flutter/current/usr/include
      - LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}/snap/flutter/current/usr/lib/$CRAFT_ARCH_TRIPLET
      - PKG_CONFIG_PATH: ${PKG_CONFIG_PATH:+$PKG_CONFIG_PATH:}/snap/flutter/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig
      - XDG_DATA_DIRS: /snap/flutter/current/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
    build-packages:
      - libusb-1.0-0-dev
      - libsqlite3-dev
      - libsqlite3-0
      - fonts-noto-cjk
    stage-packages:
      - libusb-1.0-0
      - libgtk-3-0
      - libgl1
      - fonts-noto-cjk
      - libsqlite3-0
      - libsqlite3-dev
      - locales-all
      # - libdrm-common
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/bin/lib
      mkdir fonts
      cp -r /usr/share/fonts/opentype/noto/* fonts/
      flutter channel stable
      flutter upgrade
      flutter config --enable-linux-desktop
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
  usbserver:
    plugin: python
    source: ./usbserver
    python-requirements:
      - usbserver/requirements.txt
    build-packages:
      - build-essential
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/bin/usbserver
      cp -r ./* $SNAPCRAFT_PART_INSTALL/bin/usbserver

  graphics-core22:
    after:
      - ubuntu-kr-qr-kiosk
      - gsettings+pixbuf+immodules
      - setup
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
      cd "$CRAFT_PRIME/usr/share/"
      rm -rf bug drirc.d glvnd libdrm lintian man
      rm -rf applications apport bash-completion dbus-1 doc-base doc gtk-doc\
             help pkgconfig libthai metainfo themes thumbnailers xml
    prime:
      - bin/graphics-core22-wrapper

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
